### ISSUE TITLE
import yaml

### ISSUE THREAD

**Issue by neo-chai** [Beasticle/Schoology-Bot#1]
Im using repl.it, and it is giving me the error No module named "yaml"

**Comment by julian-heidt** [comment]
Hello, 

So I used yaml to hide my API key and tokens. I noticed that you are using an online IDE so I'm not sure how your imports work but, anywhere that yaml is used you can delete and then hard code your tokens. Also make sure to replace the Schoology class IDs and what not, otherwise you'll pull from my IT class lol.
